#!/bin/sh /etc/rc.common
START=99
STOP=10
USE_PROCD=1

start_service() {
    procd_open_instance
    procd_set_param command sh -c "cd /etc/drcom && exec /usr/bin/drcom_client"
    procd_set_param respawn
    procd_set_param env PATH="/usr/sbin:/usr/bin:/sbin:/bin"
    procd_set_param env LD_LIBRARY_PATH="/usr/lib:/lib"
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}

stop_service() {
    killall -9 drcom_client
}