#!/bin/sh /etc/rc.common
START=99
STOP=10
USE_PROCD=1


start_service() {
    # 使用 procd 管理主程序
    procd_open_instance "drcom_client"
    procd_set_param service "drcom_client"
    procd_set_param command sh -c "cd /etc/drcom && exec /usr/bin/drcom_client"
    procd_set_param respawn
    procd_set_param env PATH="/usr/sbin:/usr/bin:/sbin:/bin"
    procd_set_param env LD_LIBRARY_PATH="/usr/lib:/lib"
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance

    # 使用 procd 管理网络保持活跃脚本
    procd_open_instance "drcom_keep_alive"
    procd_set_param service "drcom_client"
    procd_set_param command sh "/etc/drcom/keep_alive.sh"
    procd_set_param env PATH="/usr/sbin:/usr/bin:/sbin:/bin"
    procd_set_param respawn
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}

stop_service() {
    # 明确调用procd的kill函数来停止服务
    # 这会停止所有注册到 'drcom_client' 服务下的实例
    procd_kill "drcom_client"
}

restart() {
    stop_service
    sleep 1
    start_service
}

reload_service() {
    stop_service
    sleep 1
    start_service
}